#!/bin/bash

if [ "$(stat -c "%Y" "${APPLICATION_INST}/crowd-webapp/WEB-INF/classes/crowd-init.properties")" -eq "0" ]; then
  sed --in-place "s~#crowd.home=\/var\/crowd-home~crowd.home=${APPLICATION_HOME}~" ${APPLICATION_INST}/crowd-webapp/WEB-INF/classes/crowd-init.properties
fi

exec "$@"